### ISSUE TITLE
Local. Is it possible?

### ISSUE THREAD

**Issue by alessandroias** [lwestenberg/homeassistant_bold#7]
I admit that this is not the place to ask for buying advice, but unfortunately there is no discussion tab in this repository, and @lwestenberg seems like the best person to ask. 

I don't have this lock, but I would like to buy it. The only thing holding me back is cloud addiction. In short, I would like to remove internet access from the router. Is it possible to engineer a solution that works only in the local network? even at the cost of having to develop it independently? you already tried? do you have any idea?

**Comment by lwestenberg** [comment]
No problem to ask it here.

I don't think it's possible to run it without having a Bold account/configuring the lock with their service but I think a LAN solution is possible since you can also unlock the lock without internet on your phone or by using a bold clicker. 

This means you can have a device in your local network (e.g. an ESP32 with bluetooth) or solder a clicker to an ESP/smart switch and make it unlock your door. It could still mean you would have to update some stuff (perhaps some keys) now and then by connecting to the Bold API but it won't be connected to the Cloud all the time.
