### ISSUE TITLE
Bold HA won't connect

### ISSUE THREAD

**Issue by peetersit** [lwestenberg/homeassistant_bold#8]
Hi @lwestenberg,

When i try to install de bold HA integration. it keeps saying no connection.
What am i doing wrong or what else do i need configure?

Thanks Patrick

<img width="435" alt="image" src="https://user-images.githubusercontent.com/121575883/211142515-d4637d37-fa73-41d4-b461-1a89d6e87cde.png">

**Comment by jorgezazo** [comment]
Same here. I think some change in connection way to bold account

**Comment by bartbakels** [comment]
Maybe not the right place but i just bought also a bold and planning to use this integration. So it seems its not functional anymore?

**Comment by lwestenberg** [comment]
I just updated the source of this repo to the latest version. We are still planning to release an official HA integration. I made a fork of the HA core repo which can be found in my repositories. The only thing missing is unit tests. If there is anybody with time to help with that, it would speed up the process, since I have very little time these days.
